version: 0.1

phases:
  pre_build:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
